// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using project_payflow_backend.Data;

#nullable disable

namespace project_payflow_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250807061803_AddedNewPropertyInUserTable")]
    partial class AddedNewPropertyInUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("project_payflow_backend.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.Property<double>("WorkHours")
                        .HasColumnType("double");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("project_payflow_backend.Model.Payroll", b =>
                {
                    b.Property<int>("PayrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollId"));

                    b.Property<decimal>("AbsenceDeduction")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("AvailableLeaves")
                        .HasColumnType("int");

                    b.Property<int>("DaysAbsent")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FirstHalfPay")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LateHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("LatesDeduction")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("OverloadAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("OverloadUnits")
                        .HasColumnType("int");

                    b.Property<decimal>("PagIbig")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PayPeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PayPeriodStart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PhilHealth")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SSS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SecondHalfPay")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("PayrollId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Payrolls");
                });

            modelBuilder.Entity("project_payflow_backend.Model.PayrollReceipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PayrollId")
                        .HasColumnType("int");

                    b.Property<string>("PrintableReceiptUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiptJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ReceiptId");

                    b.HasIndex("PayrollId")
                        .IsUnique();

                    b.ToTable("PayrollReceipts");
                });

            modelBuilder.Entity("project_payflow_backend.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("project_payflow_backend.Model.Payroll", b =>
                {
                    b.HasOne("project_payflow_backend.Model.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("project_payflow_backend.Model.PayrollReceipt", b =>
                {
                    b.HasOne("project_payflow_backend.Model.Payroll", "Payroll")
                        .WithOne()
                        .HasForeignKey("project_payflow_backend.Model.PayrollReceipt", "PayrollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payroll");
                });
#pragma warning restore 612, 618
        }
    }
}
